-- Insert statements for movies with auto-generated Id
INSERT INTO "Movies" ("Title", "Description", "Genres", "Image", "ReleaseDate", "Duration", "DirectedBy", "Actors", "TicketPrice", "Trailer") 
VALUES
('Haikyuu!! The Dumpster Battle', 'Despite a strong field, the Karasuno High volleyball team advances past the preliminary round of the Harutaka tournament in Miyagi prefecture to reach the third round.', ARRAY['Anime', 'Volleyball', 'Animation', 'Drama', 'Sport', 'Comedy'], 'https://m.media-amazon.com/images/M/MV5BZWFiNmRkY2MtN2ViZC00MzhhLWI0YWYtNzVlZWFmZDI3ZjE3XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg', '2024-02-16', '1h 25m', 'Susumu Mitsunaka', ARRAY['Ayumu Murase', 'Kaito Ishikawa', 'Yuki Kaji', 'Yuichi Nakamura', 'Koki Uchiyama'], 100, 'https://www.youtube.com/embed/H51vnZt1ctU?si=7-YrrlN0n7k5ysWJ'),
('Demon Slayer: To the Hashira Training', 'Tanjiro goes to see the Stone Hashira, Himejima, who intends to prepare him for the upcoming battles. The training to become a Hashira is intense and demanding.', ARRAY['Anime', 'Action', 'Fantasy', 'Adventure'], 'https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/206c4244-ddf4-489f-bd57-e7c10f4a76a9/dgjwgor-e6c1877d-32da-43b4-8bd8-fae4c5066ff8.jpg/v1/fill/w_1280,h_1810,q_75,strp/demon_slayer_hashira_training_poster_by_angkashi_dgjwgor-fullview.jpg?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7ImhlaWdodCI6Ijw9MTgxMCIsInBhdGgiOiJcL2ZcLzIwNmM0MjQ0LWRkZjQtNDg5Zi1iZDU3LWU3YzEwZjRhNzZhOVwvZGdqd2dvci1lNmMxODc3ZC0zMmRhLTQzYjQtOGJkOC1mYWU0YzUwNjZmZjguanBnIiwid2lkdGgiOiI8PTEyODAifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6aW1hZ2Uub3BlcmF0aW9ucyJdfQ.vbq9jA2DGoSgNYw6MfXE5jvbSaDrW8ZFTXFmdU-aEe4', '2024-02-22', '1h 44m', 'Haruo Sotozaki', ARRAY['Natsuki Hanae', 'Akari Kito', 'Hiro Shimono', 'Yoshitsugu Matsuoka'], 120, 'https://www.youtube.com/embed/rq1tllAUS1I?si=NyHi7arcMuPuxWo2'),
('The First Slam Dunk', 'Ryota Miyagi, the point guard of Shohoku High''s basketball team, leads them into the Inter-High School National Championship against the reigning champions.', ARRAY['Anime', 'Sport', 'Drama', 'Animation'], 'https://i.etsystatic.com/51597930/r/il/62e568/5963917677/il_fullxfull.5963917677_lde2.jpg', '2022-12-03', '2h 04m', 'Takehiko Inoue', ARRAY['Shugo Nakamura', 'Jun Kasama', 'Shinichiro Kamio', 'Subaru Kimura'], 100, 'https://www.youtube.com/embed/l4nP-Zm9YAs?si=OW6Kov0NIKxmvNHN'),
('Jujutsu Kaisen 0', 'Yuta Okkotsu, a high schooler who gains control of an extremely powerful Cursed Spirit, is enrolled in the Tokyo Prefectural Jujutsu High School by sorcerers.', ARRAY['Anime', 'Action', 'Fantasy', 'Supernatural'], 'https://image.tmdb.org/t/p/original/23oJaeBh0FDk2mQ2P240PU9Xxfh.jpg', '2021-12-24', '1h 45m', 'Sunghoo Park', ARRAY['Megumi Ogata', 'Kana Hanazawa', 'Mikako Komatsu', 'Tomokazu Seki'], 115, 'https://www.youtube.com/embed/2docezZl574?si=JAa0PvWqHWG0XkLg'),
('Spy x Family Code: White', 'After receiving an order to be replaced in Operation Strix, Loid decides to help Anya win a cooking competition at Eden Academy by making the principal''s favorite meal.', ARRAY['Anime', 'Comedy', 'Action', 'Spy'], 'https://image.tmdb.org/t/p/original/rScguiryGULl9cPmLRBSYyqotWR.jpg', '2023-12-22', '1h 50m', 'Kazuhiro Furuhashi', ARRAY['Takuya Eguchi', 'Atsumi Tanezaki', 'Saori Hayami', 'Kenichiro Matsuda'], 105, 'https://www.youtube.com/embed/m5TxWbtQ7qU?si=QWgoFs7KFuM3QMNQ'),
('One Piece Film: Red', 'Uta — the most beloved singer in the world. Her voice, which she sings with while concealing her true identity, has been described as ''otherworldly.''', ARRAY['Anime', 'Action', 'Adventure', 'Music'], 'https://opwiki.org/images/One_Piece_Film_Red_Poster.jpg', '2022-08-06', '1h 55m', 'Goro Taniguchi', ARRAY['Mayumi Tanaka', 'Shuichi Ikeda', 'Kaori Nazuka', 'Kazuya Nakai'], 110, 'https://www.youtube.com/embed/eU0i7L3cakI?si=zZsGMtya6VNXCFgC'),
('Your Name', 'Two strangers find themselves linked in a bizarre way. When a connection forms, will distance be the only thing to keep them apart?', ARRAY['Anime', 'Romance', 'Drama', 'Fantasy'], 'https://i.pinimg.com/originals/47/2e/92/472e9277dae8a2750e32f493c0f08246.jpg', '2016-08-26', '1h 46m', 'Makoto Shinkai', ARRAY['Ryunosuke Kamiki', 'Mone Kamishiraishi', 'Ryo Narita', 'Aoi Yuki'], 95, 'https://www.youtube.com/embed/xU47nhruN-Q?si=rXSZyXLkWsPko79M'),
('Blue Lock: Episode Nagi', 'The movie follows the high school student Nagi Seishiro as he discovers his hidden talent for soccer and enters the mysterious Blue Lock facility.', ARRAY['Anime', 'Sport', 'Soccer', 'Animation'], 'https://images.librotea.com/uploads/media/2024/09/01/blue-lock-episode-nagi-n-02.jpeg', '2024-04-19', '1h 31m', 'Shunsuke Ishikawa', ARRAY['Nobunaga Shimazaki', 'Yuma Uchida', 'Kazuyuki Okitsu', 'Tasuku Kaito'], 100, 'https://www.youtube.com/embed/6NCsj0anAt8?si=6Zx-IzpV0AFUOnXQ'),
('Kaguya-Sama: Love is War - The First Kiss That Never Ends', 'Now that Kaguya and Miyuki have shared their first kiss, the time has come for them to truly understand each other and admit their feelings as the winter holidays begin.', ARRAY['Anime', 'Romance', 'Comedy', 'Drama'], 'https://image.tmdb.org/t/p/w1280/8uptbtuAyGQp7mxYhVMpmxu3TGp.jpg', '2022-12-17', '1h 36m', 'Shinichi Omata', ARRAY['Aoi Koga', 'Makoto Furukawa', 'Konomi Kohara', 'Ryota Suzuki', 'Yumiri Hanamori'], 120, 'https://www.youtube.com/embed/W3IvBLpebQ4?si=B_d_QmGylbRxpQVU');

-- Insert statements for TimeSlots table
INSERT INTO "TimeSlots" ("TimeSlot") 
VALUES
('09:00:00'),
('11:00:00'),
('13:45:00'),
('16:45:00'),
('19:45:00');